### ISSUE TITLE
通过require来引用外部Mock数据会有缓存问题

### ISSUE THREAD

**Issue by YunyChan** [luobotang/jsp-renderer#1]
每次我修改完mock数据后，因为jsp-renderer通过node的require引用数据，而require会把第一次加载的数据缓存住。这导致修改无法生效，必须重启Node后才能让修改生效。所以得在每次读取本地mock数据时把缓存清掉。

建议在jsp-renderer的index.js中的getData函数require mock数据前执行以下语句清掉缓存：
`delete require.cache[require.resolve(path)]`

**Comment by luobotang** [comment]
感谢使用，我会尽快处理

**Comment by luobotang** [comment]
@YunyChan v0.1.4 已修复

**Comment by YunyChan** [comment]
页面自己的数据已经没问题了，但是global-data因为闭包的缘故，修改global-data还是取的是第一次加载的值

**Comment by luobotang** [comment]
@YunyChan v0.1.5 已修复 global-data 不更新的问题
